# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79260bf05b1395fbcf8dce9d4a2aa2a217dc8a48ae2485348ab8a7787eb1f89e62ea215ae3091ebef00ee23a74958b459fddb5819236d786b049773506345d30

test:
  secret_key_base: be2cb8a4a782a3142dc55e2105d62b377ea9d2e8e3273c85b9a0cab6b662232d274b94336187971eb926cfc7bd6358fc50a8d21429d4aa7b8082df2b7dba80f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
